image: nixos/23.11
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://git.sr.ht/~shom/shom.dev
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
  site: shom.dev
tasks:
  - build: |
      cd $site
      #Only build and deploy main branch
      # if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
      # complete-build; \
      # fi
      nix develop --command ./build.sh --gc
  - deploy: |
      cd $site
      cd public
      tar -cvz . > ../site.tar.gz
      cd ..
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
