image: archlinux
packages:
  - emacs-nox
  - exiftool
  - hugo
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://git.sr.ht/~shom/shom.dev
environment:
  site: shom.dev
tasks:
  - build: |
      cd $site
      ./build.sh
  - deploy: |
      cd $site
      cd public
      tar -cvz . > ../site.tar.gz
      cd ..
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
