image: ubuntu/22.04
packages:
  - emacs-nox
  - libimage-exiftool-perl
  - hugo
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://git.sr.ht/~shom/shom.dev
environment:
  site: shom.dev
tasks:
  - build: |
      #Only build and deploy main branch
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
      complete-build; \
      fi
      cd $site
      ./build.sh
  - deploy: |
      cd $site
      cd public
      tar -cvz . > ../site.tar.gz
      cd ..
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
  - exit: |
      echo "Exiting"
          
