repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
- repo: local
  hooks:
    - id: checklinks
      name: "Check for broken links"
      entry: checklinks.sh
      language: script
      pass_filenames: false
      verbose: true
