image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://git.sr.ht/~shom/shom.dev
environment:
  site: shom.dev
tasks:
  # - build: |
      # cd site
      # emacs --batch -l ./publish.el --funcall publish/sb
  - package: |
      cd public
      tar -cvz . > ../site.tar.gz
  - upload: |
      acurl --fail-with-body https://pages.sr.ht/publish/$site -Fcontent=@public.tar.gz
