baseURL: "https://shom.dev"
languageCode: "en-us"
title: "shom.dev"
theme: "PaperMod"

params:
    env: production
    defaultTheme: dark
    ShowReadingTime: true
    #ShowShareButtons: true
    #ShowToc: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowFullTextinRSS: true
    ShowCodeCopyButtons: true
    disableScrollToTop: true
    showtoc: true
    tocopen: false
    hideFooter: true
    assets:
      disableHLJS: true
    homeInfoParams:
        enabled: true
        Title: Shom Bandopadhaya
        Content: "I like people, dogs, photography, scuba-diving, computers, open-source software, privacy, and generally improving things where I can."
    profileMode:
        enabled: false
        title: "Shom Bandopadhaya" # optional default will be site title
        subtitle: "More curiosity than time"
        #imageUrl: "<image link>" # optional
        #imageTitle: "<title of image as alt>" # optional
#        imageWidth: 120 # custom size
#        imageHeight: 120 # custom size
    # buttons:
    #   - name: Archives
    #     url: "/posts"
    #     name: Tags
    #     url: "/tags"
    socialIcons: # optional
        - name: 'Mastodon'
          url: 'https://fosstodon.org/@shom'
        - name: 'camera'
          url: 'https://photos.shom.dev'
        - name: 'git'
          url: 'https://git.sr.ht/~shom'
        - name: 'Github'
          url: 'https://github.com/shombando'
        - name: 'LinkedIn'
          url: 'https://www.linkedin.com/in/shom'
        - name: 'key'
          url: 'https://id.shom.dev'
        - name: 'RSS'
          url: 'https://shom.dev/index.xml'
markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: nord
  goldmark:
    renderer:
      unsafe: true # This is *necessary* for ox-hugo to work well with Hugo 0.60.0+
