baseURL: "https://shom.dev"
languageCode: "en-us"
title: "shom.dev"
theme: "PaperMod"

params:
    defaultTheme: auto
    ShowReadingTime: true
    #ShowShareButtons: true
    #ShowToc: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowFullTextinRSS: true
    ShowCodeCopyButtons: true
    disableScrollToTop: true
    showtoc: true
    tocopen: false
    hideFooter: true
    homeInfoParams:
        enabled: true
        Title: Shom Bandopadhaya
        Content: "I like people, dogs, photography, scuba-diving, computers, open-source software, privacy, and generally improving things where I can."
    profileMode:
        enabled: false
        title: "Shom Bandopadhaya" # optional default will be site title
        subtitle: "More curiosity than time"
        #imageUrl: "<image link>" # optional
        #imageTitle: "<title of image as alt>" # optional
#        imageWidth: 120 # custom size
#        imageHeight: 120 # custom size
    # buttons:
    #   - name: Archives
    #     url: "/posts"
    #     name: Tags
    #     url: "/tags"
    socialIcons: # optional
        - name: 'Github'
          url: 'https://github.com/shombando'
        - name: 'gitea'
          url: 'https://codeberg.org/shom'
        - name: 'Mastodon'
          url: 'https://fosstodon.org/@shom'
        - name: 'LinkedIn'
          url: 'https://www.linkedin.com/in/shom'
        - name: 'Keybase'
          url: 'https://keybase.io/sbando'
        - name: 'instagram'
          url: 'https://shom.bandopadhaya.com/photos/'
        - name: 'RSS'
          url: 'https://shom.dev/index.xml'
    #    - name: "<platform 2>"
    #        url: "<link2>"
