on: [push]

jobs:
  build:
    runs-on: docker #tag associated with runner
    container:
      image: ghcr.io/nixos/nix
    steps:
      - name: Secrets
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/forgejo
          chmod 600 ~/.ssh/forgejo
          echo "${{ secrets.CONMAN_SSH_KEY }}" > ~/.ssh/conman
          chmod 600 ~/.ssh/conman
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: Checkout
        env:
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/forgejo -p 222"
        run: |
          #from https://codeberg.org/nix-actions/checkout/src/branch/main/action.yml
          set -x
          git clone -b $GITHUB_REF_NAME git@git.shom.dev:shom/shom.dev.git --depth=1
          cd shom.dev
          git submodule init
          git submodule update
      - name: Build site
        env:
          NIX_CONFIG: "experimental-features = nix-command flakes"
          site: shom.dev
        run: |
          cd shom.dev
          nix develop --command ./build.sh --gc
      - name: Deploy
        run: |
          cd shom.dev
          echo "deploy test" > deploy.txt
          nix run nixpkgs#rsync 'ssh -p 222' ./deploy.txt conman@git.shom.dev:~/prod/caddy/site/shom.dev
