on: [push]

jobs:
  build:
    runs-on: docker #tag associated with runner
    container:
      image: git.shom.dev/shom/nixos:emacs29
    steps:
      - name: Secrets
        run: |
          echo "Adding keys to .ssh"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/forgejo
          chmod 600 ~/.ssh/forgejo
          echo "${{ secrets.CONMAN_SSH_KEY }}" > ~/.ssh/conman
          chmod 600 ~/.ssh/conman
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "Keys added"
      - name: Checkout
        env:
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/forgejo -p 222"
        run: |
          #from https://codeberg.org/nix-actions/checkout/src/branch/main/action.yml
          set -x
          git clone -b $GITHUB_REF_NAME git@git.shom.dev:shom/shom.dev.git --depth=1
          cd shom.dev
          git submodule init
          git submodule update
      - name: Build site
        env:
          NIX_CONFIG: "experimental-features = nix-command flakes"
          site: shom.dev
        run: |
          cd $site
          echo "Building with nix"
          nix develop --command ./build.sh --gc
      - name: Deploy
        env:
          NIX_CONFIG: "experimental-features = nix-command flakes"
          site: shom.dev
        run: |
          cd $site
          echo "Deploying with rsync"
          rsync -- -e 'ssh -i ~/.ssh/conman -p 22' --archive --progress ./public/* conman@107.175.0.178:/home/conman/prod/caddy/site/shom.dev/
